Models/Clothes.cs
using Microsoft.AspNetCore.Http;
using MultiShop.Models.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MultiShop.Models
{
    public class Clothes:BaseEntity
    {
        public string Image { get; set; }
        [Required, StringLength(maximumLength: 25)]
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Text { get; set; }
        public string Desc { get; set; }
        public int InformationId{ get; set; }
        public ClothesInformation ClothesInformation { get; set; }
        public List<ClothesCategory> ClothesCategories { get; set; }
         [NotMapped]
        public List<int> CategoryIds { get; set; }
        public List<ClothesImage> ClothesImages { get; set; }
        [NotMapped]
        public List<int> ImageId { get; set; }
        [NotMapped]
        public IFormFile MainPhoto { get; set; }
        [NotMapped]
        public List<IFormFile> Photos { get; set; }

        //public List<ClothesColor> ClothesColors { get; set; }
        //public List <ClothesSizes> ClothesSizes { get; set; }
    }
}

Areas/MultiShopadmin/Controllers/ClothesController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MultiShop.DAL;
using MultiShop.Models;
using MultiShop.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MultiShop.Areas.MultiShopadmin.Controllers
{
    [Area("MultiShopadmin")]

    public class ClothesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _env;

        public ClothesController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            List<Clothes> clothes = await _context.Clothes.Include(p => p.ClothesImages)
                .Include(p => p.ClothesCategories)
                .ThenInclude(pc => pc.Category)
                .ToListAsync();

            return View(clothes);
        }
        public IActionResult Create()
        {
            ViewBag.Information = _context.clothesInformations.ToList();
            ViewBag.Categories = _context.Categories.ToList();
            return View();
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(Clothes clothes)
        {
            ViewBag.Information = _context.clothesInformations.ToList();
            ViewBag.Categories = _context.Categories.ToList();
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (clothes.MainPhoto == null || clothes.Photos == null)
            {

                ModelState.AddModelError(string.Empty, "must choose 1 main photo");
                return View();
            }
            if (!clothes.MainPhoto.ImageIsOkay(2))
            {

                ModelState.AddModelError(string.Empty, "choose image file");
                return View();
            }

            clothes.Image = await FileValidator.FileCreate(clothes.MainPhoto, _env.WebRootPath, "assets/img");

            ClothesImage mainimage = new ClothesImage
            {
                IsMain = true,
                Name = await FileValidator.FileCreate(clothes.MainPhoto, _env.WebRootPath, "assets/img")
            };
           

            clothes.ClothesImages = new List<ClothesImage>();

            clothes.ClothesImages.Add(mainimage);

            clothes.ClothesCategories = new List<ClothesCategory>();

            if (clothes.Photos.Count < 0)
            {
                ModelState.AddModelError("", "choose image file");
                return View();
            }

            foreach (IFormFile file in clothes.Photos)
            {
                if (!file.ImageIsOkay(2))
                {
                    ModelState.AddModelError(string.Empty, "choose valid image file");
                    return View();
                }

                ClothesImage clothesImage = new ClothesImage
                {
                    IsMain = false,
                    Clothes = clothes,
                    Name = await FileValidator.FileCreate(file, _env.WebRootPath, "assets/img")
                };
                clothes.ClothesImages.Add(clothesImage);
            }

            foreach (int id in clothes.CategoryIds)
            {
                ClothesCategory clothesCategory = new ClothesCategory
                {
                    CategoryId = id,
                    Clothes = clothes
                };

                clothes.ClothesCategories.Add(clothesCategory);
            };

            _context.Clothes.Add(clothes);

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Detail(int? id)
        {
            if (id == null || id == 0) return NotFound();
            Clothes clothes = _context.Clothes.SingleOrDefault(c => c.Id == id);
            if (clothes == null) return NotFound();
            return View(clothes);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.Information = _context.clothesInformations.ToList();
            ViewBag.Categories = _context.Categories.ToList();
            ViewBag.ClothesCategories=_context.ClothesCategories.Where(c=>c.ClothesId==id).ToList();
            if (id == 0 || id == null) return NotFound();
            if (!ModelState.IsValid) return View();
            Clothes clothes = await _context.Clothes
                .Include(c => c.ClothesImages)
                .Include(c => c.ClothesInformation)
                .Include(c => c.ClothesCategories).SingleOrDefaultAsync(c => c.Id == id);
            if (clothes == null) return NotFound();
            return View(clothes);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(int? id, Clothes clothes)
        {
            if (id == 0 || id == null) return NotFound();
            Clothes existed = await _context.Clothes
               .Include(c => c.ClothesImages)
               .Include(c => c.ClothesInformation)
               .Include(c => c.ClothesCategories).FirstOrDefaultAsync(c => c.Id == id);
            if (!ModelState.IsValid) return View(existed);
            if (existed == null) return NotFound();
            List<ClothesImage> clothesImages = existed.ClothesImages.Where(c => c.IsMain == true &&
            !clothes.ImageId.Contains(c.Id)).ToList();

            _context.Entry(existed).CurrentValues.SetValues(clothes);
            existed.ClothesImages.RemoveAll(c => clothesImages.Any(r => c.Id == r.Id));

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0) return NotFound();
            Clothes clothes = await _context.Clothes.FindAsync(id);
            if (clothes == null) return NotFound();
            _context.Clothes.Remove(clothes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/ClothesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MultiShop.DAL;
using MultiShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MultiShop.Controllers
{
    public class ClothesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClothesController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Detail(int? id)
        {
            if (id == 0 || id is null) return NotFound();
            Clothes clothes = _context.Clothes.Include(c => c.ClothesImages).Include(c => c.ClothesInformation).FirstOrDefault(c => c.Id == id);
            if (clothes == null) return NotFound();
            return View(clothes);
        }
    }
}

Areas/MultiShopadmin/Views/Clothes/Create.cshtml
@model Clothes
@{
    ViewData["Title"] = "Create";
}
<main class="main-panel">
    <h1 style="text-align:center; background-color:grey">Create Clothes</h1>
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
    <form method="post" class="mt-2" enctype="multipart/form-data">
        <div>
            <label>Main:</label><br />
            <input asp-for="MainPhoto" class="form-control" /><br />
            <span classs="text-danger" asp-validation-for="MainPhoto"></span>
        </div>
        <div>
            <label>Images:</label><br />
            <input asp-for="Photos" class="form-control" /><br />
            <span classs="text-danger" asp-validation-for="Photos"></span>
        </div>
        <div>
            <label>Name:</label><br />
            <input asp-for="Name" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div>
            <label>Price:</label><br />
            <input asp-for="Price" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Price"></span>
        </div>
        <div>
            <label>Text:</label><br />
            <input asp-for="Text" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Text"></span>
        </div>
        <div>
            <label>Desc:</label><br />
            <input asp-for="Desc" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Desc"></span>
        </div>
        <div>
            <label>Clothes Information:</label><br />
            <span class="text-danger" asp-validation-for="InformationId"></span>
            <select class="form-control" asp-for="InformationId"
                    asp-items="@(new SelectList(ViewBag.Information,"Id","Information"))"></select>
        </div>
        <div>
            <label>Clothes Category:</label><br />
            <select class="form-control" asp-for="CategoryIds"
                    asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))"></select>
        </div>
        <div class="mt-2">
            <button class="btn btn-success" type="submit">
                Create
            </button>
        </div>
    </form>
</main>

Areas/MultiShopadmin/Views/Clothes/Detail.cshtml
@model MultiShop.Models.Clothes

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>Clothes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class="col-sm-10">
            <img src="~/assets/img/@Model.Image" alt="" />
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InformationId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InformationId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/MultiShopadmin/Views/Clothes/Edit.cshtml
@model Clothes
@{
    ViewData["Title"] = "Edit";

    List<ClothesCategory> categories = (List<ClothesCategory>)ViewBag.ClothesCategories;
}
<main class="main-panel">
    <h1 style="text-align:center; background-color:grey">Create Clothes</h1>
    @if (TempData["Filname"] != null)
    {
        <div class="alert alert-danger">@TempData["Filename"]</div>
    }
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
    <form method="post" class="mt-2" enctype="multipart/form-data">
        <div>
            <label>Main Photo:</label><br />
            <input asp-for="MainPhoto" class="form-control" /><br />
            <span classs="text-danger" asp-validation-for="MainPhoto"></span>
        </div>
        <div>
            <label>Images:</label><br />
            <input asp-for="Photos" class="form-control" /><br />
            <span classs="text-danger" asp-validation-for="Photos"></span>
        </div>
        <div class="images">
            <div class="images">
                <h3>Main</h3>
                <img src="~/assets/img/@Model.ClothesImages.FirstOrDefault(p=>p.IsMain == true).Name">
            </div>
            <h3>Other images</h3>
            <div class="image d-flex">

                @foreach (ClothesImage image in Model.ClothesImages.Where(p => p.IsMain == false))
                {
                    <div style="position:relative;" class="col-sm-3">
                        <img src="~/assets/img/@image.Name" style="width:100%;height:200px;object-fit:contain">
                        <input type="hidden" name="ImagesId" value="@image.Id">
                        <button style="position:absolute; right:5px" type="button" class="btn btn-success remove">X</button>
                    </div>
                }
            </div>
        </div>
        <div>
            <label>Name:</label><br />
            <input asp-for="Name" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div>
            <label>Price:</label><br />
            <input asp-for="Price" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Price"></span>
        </div>
        <div>
            <label>Text:</label><br />
            <input asp-for="Text" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Text"></span>
        </div>
        <div>
            <label>Desc:</label><br />
            <input asp-for="Desc" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Desc"></span>
        </div>
        <div>
            <label>Clothes Information:</label><br />
            <select class="form-control" asp-for="InformationId" asp-items="@(new SelectList(ViewBag.Information,"Id","Information"))"></select>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.CategoryIds" class="form-label">Authors</label>
            <select asp-for="@Model.CategoryIds" class="form-select">
                @foreach (var category in (List<Category>)ViewBag.Categories)
                {
                    if (Model.ClothesCategories.FirstOrDefault(c => c.CategoryId == category.Id) != null)
                    {
                        <option value="@category.Id" selected>@category.Name</option>
                    }
                    else
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                }
            </select>
            <span class="mt-2 text text-danger" asp-validation-for="@Model.CategoryIds"></span>
        </div>
        <div class="mt-5">
            <button class="btn btn-success" type="submit"> Update </button>
        </div>
    </form>
</main>
@section Scripts{
    <script>
        let btns = document.querySelectorAll(".remove")

        btns.forEach(b => {
            b.addEventListener("click", function () {
                b.parentElement.remove();
            })
        })
    </script>
}

Areas/MultiShopadmin/Views/Clothes/Index.cshtml
@model List<Clothes>
@{
    ViewData["Title"] = "Index";
}
<div class="main-panel">
    <div>
        <a class="btn btn-success" asp-area="MultiShopadmin" asp-controller="clothes" asp-action="Create">
            Create New Plant
        </a>
    </div>
    @if (TempData["FileName"] != null)
    {
        <div class="alert alert-danger">@TempData["FileName"]</div>
    }
    <div class="table-responsive pt-3">
        <table class="table table-dark">
            <thead>
                <tr>
                    <th>
                        Image
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        Text
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Settings
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (Clothes clothes in Model)
                {
                    <tr>
                        <td>
                            <img style="width:110px; height:110px"
                                 src="~/assets/img/@clothes.ClothesImages.FirstOrDefault(c=>c.IsMain==true).Name" />
                        </td>
                        <td>
                            @clothes.Name
                        </td>
                        <td>
                            @clothes.Price
                        </td>
                        <td>
                            @clothes.Text
                        </td>
                        <td>
                            @clothes.Desc
                        </td>
                        <td class="d-flex align-items-center" style="height:155px">
                            <div>
                                <a asp-area="MultiShopadmin" asp-controller="Clothes" asp-action="Edit" asp-route-id="@clothes.Id"
                                   class="btn btn-warning"><i class="mdi mdi-border-color"></i></a>
                            </div>
                            <div>
                                <a asp-area="MultiShopadmin" asp-controller="Clothes" asp-action="Delete" asp-route-id="@clothes.Id"
                                   class="btn btn-primary"><i class="mdi mdi-delete"></i></a>
                            </div>
                            <div>
                                <a asp-area="MultiShopadmin" asp-controller="clothes" asp-action="Detail" asp-route-id="@clothes.Id"
                                   class="btn btn-success"><i class="mdi mdi-information"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>